backend:
  name: github
  repo: lxdb-team/fossplanet
  branch: master
  site_domain: www.foss-planet.de

media_folder: "/static/images/post"
public_folder: "/images/post/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog/"
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
